// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const isVercel = process.env.VERCEL === "1" || Boolean(process.env.VERCEL_ENV);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // ✅ Local => DATABASE_URL
    // ✅ Vercel => TURSO_DATABASE_URL
    url: isVercel ? env("TURSO_DATABASE_URL") : env("DATABASE_URL"),
  },
});
